# Generated by Django 6.0.4 on 2026-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('eSewa', 'eSewa'), ('Khalti', 'Khalti'), ('IME Pay', 'IME Pay'), ('Fonepay', 'Fonepay'), ('ConnectIPS', 'ConnectIPS'), ('nPay', 'nPay'), ('NIC Asia Bank', 'NIC Asia Bank'), ('Nabil Bank', 'Nabil Bank'), ('Global IME Bank', 'Global IME Bank'), ('Everest Bank', 'Everest Bank'), ('Kumari Bank', 'Kumari Bank'), ('Sanima Bank', 'Sanima Bank')], default='Cash', max_length=50),
        ),
    ]
